### ISSUE TITLE
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'ClickHouseDialect_native' object has no attribute '_json_serializer

### ISSUE THREAD

**Issue by AllenCHM** [xzkostyan/clickhouse-sqlalchemy#114]
when I insert data

Traceback (most recent call last):
  File "kafka_alarm_filter.py", line 354, in consume_kafka_data
    NetAttackSituation.ch_create(**res)
  File "/data/SecOMP/somp/models/base.py", line 45, in ch_create
    cls.__table__.insert(), [kwargs]
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1292, in execute
    clause, params or {}
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1207, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 821, in _init_compiled
    processors = compiled._bind_processors
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 883, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 660, in _bind_processors
    for bindparam in self.bind_names
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 654, in <genexpr>
    (key, value)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 660, in <genexpr>
    for bindparam in self.bind_names
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 499, in _cached_bind_processor
    d["bind"] = bp = d["impl"].bind_processor(dialect)
  File "/home/app/ENV3.6/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 2428, in bind_processor
    json_serializer = dialect._json_serializer or json.dumps
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'ClickHouseDialect_native' object has no attribute '_json_serializer
'

version info:
SQLAlchemy == 1.3.19
clickhouse-sqlalchemy == 0.1.4
clickhouse-driver == 0.1.5

**Comment by xzkostyan** [comment]
How should I reproduce the bug?

**Comment by xzkostyan** [comment]
Closing due to inactivity.
