### ISSUE TITLE
Unable to read metadata of table with Nullable columns. 

### ISSUE THREAD

**Issue by hodgesrm** [xzkostyan/clickhouse-sqlalchemy#124]
**Describe the bug**
Driver fails with `AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_nullable'` if you attempt to use MetaData and Table classes to show the column type. 

**To Reproduce**
First create the following table in ClickHouse. 
```
CREATE TABLE superset_test
(
    `basic_string` String,
    `nullable_string` Nullable(String),
    `lowcard_string` LowCardinality(String),
    `basic_datetime` DateTime,
    `nullable_datetime` Nullable(DateTime),
    `int_with_codec` UInt64 CODEC(Delta, ZSTD(1))
)
ENGINE = TinyLog 
```

Now run the following Python script. 
```
from sqlalchemy import create_engine, MetaData, Table
url = 'clickhouse+native://localhost/foo'
engine = create_engine(url, echo=False)
meta = MetaData(bind=engine, reflect=False)
table = Table('superset_test', meta, autoload=True, autoload_with=engine)
print(f'Name: {table.name}')
print(f'Schema: {table.schema}')
for col in table.columns:
    print(f'Column Name: {col.name}')
    print(f'       Type: {col.type}')
    print(f'       Nullable: {col.nullable}')
```
It fails with the following stack trace:
```
python3 sqa-table-meta.py 
Name: superset_test
Schema: None
Column Name: basic_string
       Type: VARCHAR
       Nullable: True
Column Name: nullable_string
Traceback (most recent call last):
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 89, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_nullable'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sqa-table-meta.py", line 11, in <module>
    print(f'       Type: {col.type}')
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 622, in __str__
    return str(self.compile())
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/sql/type_api.py", line 605, in compile
    return dialect.type_compiler.process(self)
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 93, in _compiler_dispatch
    replace_context=err,
  File "/home/rhodges/altinity/presentations/python/superset/clickhouse-sqlalchemy/clickhouse-sqlalchemy/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f0ec1d3ae10> can't render element of type <class 'clickhouse_sqlalchemy.types.common.Nullable'> (Background on this error at: http://sqlalche.me/e/13/l7de)
```

**Expected behavior**
The program should print the type VARCHAR and set the nullable property on the Column object. (This does not seem to be set correctly for any column.)

**Versions**
```
$ python --version
Python 3.7.9
$ pip freeze|grep clickhouse
clickhouse-driver==0.2.0
clickhouse-sqlalchemy==0.1.5
```

**Comment by filimonov** [comment]
https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/15

**Comment by hodgesrm** [comment]
I have tested the columns compilation fix and confirm it addresses problems with determining the type name.  The code does not set the Nullable property.  It seems that this property should be set but the SQLAlchemy behavior is not very clear in this case, since the NULL/NOT NULL property is embedded in the native type name.

**Comment by xzkostyan** [comment]
Fix has been merged into master.
