### ISSUE TITLE
Can't connect to  when clickhouse cluster one node is down with high availability.

### ISSUE THREAD

**Issue by jingcheng88** [xzkostyan/clickhouse-sqlalchemy#171]
**Describe the bug**
I connected clickhouse with superest and clickhouse-sqlalchemy. Clickhouse cluster  is high availability. But there would be exception when one clickhouse node was down.

```
Code: 210, e.displayText() = DB::NetException: Host not found: chi-ck-ck-2-0 (chi-ck-ck-2-0:9000)

: While executing Remote. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8febd9a in /usr/bin/clickhouse
1. PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x10ff34b5 in /usr/bin/clickhouse
2. DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) @ 0x10ff206d in /usr/bin/clickhouse
3. DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&) @ 0x10ff23a8 in /usr/bin/clickhouse
4. ? @ 0xfe717b3 in /usr/bin/clickhouse
5. DB::RemoteQueryExecutor::sendQuery() @ 0xfe68a2f in /usr/bin/clickhouse
6. DB::RemoteSource::tryGenerate() @ 0x112cd567 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0x11100bfa in /usr/bin/clickhouse
8. DB::SourceWithProgress::work() @ 0x112d381b in /usr/bin/clickhouse
9. ? @ 0x1113b91d in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x111384b1 in /usr/bin/clickhouse
11. ? @ 0x1113cf56 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x902ca1f in /usr/bin/clickhouse
13. ? @ 0x9030303 in /usr/bin/clickhouse
14. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
15. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Versions**

- 0.18

**Comment by xzkostyan** [comment]
This exception looks like network issue. You can specify `alt_hosts` parameter in connect string for multiple hosts support: https://clickhouse-driver.readthedocs.io/en/latest/features.html#multiple-hosts

**Comment by jingcheng88** [comment]
Clickhouse is running on kubernetes. I connect clickhouse with kubernetes serivces.
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    res = engine.execute(DDL(f'select count(*)  from data_pipeline.inceptio_truck_data_heartbeat_ados'))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 1165, in do_execute
    cursor.execute(statement, parameters, context=context)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/native/connector.py", line 158, in execute
    raise DatabaseException(orig)
clickhouse_sqlalchemy.exceptions.DatabaseException: Orig exception: Code: 279.
DB::Exception: All connection tries failed. Log:

```

**Comment by xzkostyan** [comment]
`clickhouse+native://host1:port1/db?alt_hosts=host2:port2;host3:port3`. Port is optional.
`clickhouse+native://chi-ck-ck-2-0/db?alt_hosts=chi-ck-ck-2-1;chi-ck-ck-2-2`.

**Comment by jingcheng88** [comment]
It does not work.

**Comment by xzkostyan** [comment]
Could you post additional info: your full dsn, error, etc.?

**Comment by xzkostyan** [comment]
Not enough information. Feel free to reopen with additional info.
