### ISSUE TITLE
NotImplementedError for MV

### ISSUE THREAD

**Issue by adam-mrozik** [xzkostyan/clickhouse-sqlalchemy#177]
Hey,

I am trying to run your example with MV from docs. Tables get created successfully, but MaterializedView raises NotImpemented Error.

Code:

```
from clickhouse_sqlalchemy import get_declarative_base, types, engines, MaterializedView, select
from clickhouse_sqlalchemy.sql.ddl import ttl_delete
from sqlalchemy import create_engine, Column, MetaData, func

uri = 'clickhouse+native://...'
engine = create_engine(uri)
metadata = MetaData(bind=engine)

Base = get_declarative_base(metadata=metadata)


class Statistics(Base):
    date = Column(types.Date, primary_key=True)
    sign = Column(types.Int8, nullable=False)
    grouping = Column(types.Int32, nullable=False)
    metric1 = Column(types.Int32, nullable=False)
    metric2 = Column(types.Int32, nullable=False, clickhouse_codec=('DoubleDelta', 'ZSTD'))

    __table_args__ = (
        engines.ReplicatedMergeTree(
            table_path='/clickhouse/{installation}/{cluster}/tables/{shard}/yellow/{table}',
            replica_name='{replica}',
            partition_by=func.toYYYYMMDD(date),
            order_by=(date),
            ttl=ttl_delete(date + func.toIntervalDay(10))
        ),
        {'clickhouse_cluster': '{cluster}'}
    )


# Define storage for Materialized View
class GroupedStatistics(Base):
    date = Column(types.Date, primary_key=True)
    metric1 = Column(types.Int32, nullable=False)
    metric2 = Column(types.Int32, nullable=False, clickhouse_codec=('DoubleDelta', 'ZSTD'))

    __table_args__ = (
        engines.ReplicatedMergeTree(
            table_path='/clickhouse/{installation}/{cluster}/tables/{shard}/yellow/{table}',
            replica_name='{replica}',
            partition_by=func.toYYYYMMDD(date),
            order_by=(date),
            ttl=ttl_delete(date + func.toIntervalDay(10))
        ),
        {'clickhouse_cluster': '{cluster}'}
    )


# Define SELECT for Materialized View
GroupedStatisticsMV = MaterializedView(GroupedStatistics, select([
    Statistics.date.label('date'),
    func.sum(Statistics.metric1 * Statistics.sign).label('metric1')
]).where(
    Statistics.grouping > 42
).group_by(
    Statistics.date
))

Statistics.__table__.create()
GroupedStatistics.__table__.create()
GroupedStatisticsMV.create()

```

Error:
```
Traceback (most recent call last):
  File "file.py", line 61, in <module>
    GroupedStatisticsMV.create()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/sql/schema.py", line 118, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst,
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/interfaces.py", line 1517, in _run_visitor
    raise NotImplementedError()
NotImplementedError

```

Env (fresh docker):
```
root@myPC:/# pip freeze
backports.zoneinfo==0.2.1
certifi==2022.5.18.1
charset-normalizer==2.0.12
clickhouse-driver==0.2.3
clickhouse-sqlalchemy==0.2.0
greenlet==1.1.2
idna==3.3
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
requests==2.27.1
SQLAlchemy==1.4.37
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.9
```

**Comment by xzkostyan** [comment]
I haven't publish 0.2.1 version with fixes from 0.1.9 and 0.1.10. It will be published within this week. You can install it directly from master.

**Comment by adam-mrozik** [comment]
@xzkostyan Thank you for the quick answer.

Unfortunately both master and version-0.2.1 branches result in the same NotImplementedError for me.


Also, I seem to be unable to make migrations from Docs operable. I have used your example project files, but these two commands below result in empty migrations:
```
alembic revision -m "create init state"
alembic upgrade head
```

Resulting file in versions:
```
"""create init state

Revision ID: 91f1bd9b3714
Revises: 
Create Date: 2022-06-09 16:10:33.695423

"""
from alembic import op
import clickhouse_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f1bd9b3714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
```

**Comment by xzkostyan** [comment]
I'll take a look before release. Meanwhile you can try 0.1.10 for SA 1.3

**Comment by xzkostyan** [comment]
@adam-mrozik you should always check your migration and adapt it if it's necessary. Alembic does a lot in autogeneration but it is not a sliver bullet.

Alembic generates `existing_type` for pure SQLAlchemy and psycopg2 for example. Just delete this parameter.

BTW, what changes in table produce such migration? Adding `server_default` or changing `nullable` to True?

**Comment by xzkostyan** [comment]
1. Try to define LowCardinality column as `types.LowCardinality(types.String())`. String is instance here.

2. About freeze: 0.2.0 (if you are still using it) has bug with inline literals rendering. It can cause your freeze.

3. > My setup is tricky overall, because I have a distributed cluster and it seems alembic_version table is created randomly on a current shard only. Normally you solve it by sth like create table alembic_version_local on cluster '{cluster}' + creating distributed table pointing to these local ones, but I am not sure what to edit to ensure it works properly.

We've been using migrations on cluster with following `run_migrations_online` tuning:

```python
    try:
        with context.begin_transaction():
            cluster = config['CLICKHOUSE_CLUSTER']

            if cluster:
                migration_context = context._proxy._migration_context
                kwargs = {
                    'cluster': cluster,
                    'table_path': make_replicated_zk_path(cluster, migration_context.version_table),
                    'replica_name': '{replica}'
                }
            else:
                kwargs = {}

            patch_alembic_version(context, **kwargs)
            context.run_migrations()
    finally:
        connection.close()

def make_replicated_zk_path(cluster, table_name):
    database = make_url(config['CLICKHOUSE_DATABASE_URI']).database
    return f'/clickhouse/tables/{cluster}/{database}/{table_name}'
```

This will add `ON CLUSTER xxx` during `alembic_version` table creation.

**Comment by xzkostyan** [comment]
Version 0.2.1 is released, so I'm closing this issue.

Feel free to open another one is you still have problems with migrations.
