### ISSUE TITLE
Inconsistency with Simultaneous Query returing Failed to establish a new connection:Connection timed 

### ISSUE THREAD

**Issue by gr8Adakron** [xzkostyan/clickhouse-sqlalchemy#238]
**Describe the bug**

Our Clickhouse is deployed in separate internal network VM on size 16 GB Memory and 4 CPU cores. 
Receiving inconsistent timeout while running simultaneous queries via clickhouse-sqlalchemy -- described error below in detail.

> Crucial point to Highlight: After getting timeout on client, Server is intact. We are able to navigate to Clickhouse dashbaord and fire query manually. Hence its not as such that clickhouse is going down.

**UseCase:** 
  * To fire 5K+ fetch query simultaneously via python application. 
  * This 5K+ query run once every hour in cron execution fashion.
  
**Error**: 
* After 2 or 3 execution that is on hourly basis -- all task begins to fails with below error
*  If I restart the application running in Kuberentes then upcoming few cron runs without any issues.

```
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
util.raise_(exc_info[1], with_traceback=exc_info[2])
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    ret = self._execute_context(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    return connection._execute_clauseelement(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return self.execute(object_, *multiparams, **params).scalar()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1171, in scalar
    return f(sql, **kwargs)
File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/base.py", line 52, in _execute
    version = self._execute(
File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 423, in _get_server_version_info
    self.server_version_info = self._get_server_version_info(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 407, in initialize
    super(ClickHouseDialect, self).initialize(connection)
File "/usr/local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 130, in initialize
    dialect.initialize(c)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 686, in first_connect
    return once_fn(*arg, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1691, in go
    fn(*args, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    self(*args, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    pool.dispatch.connect.for_modify(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    return _ConnectionRecord(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return self._create_connection()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    self._dec_overflow()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    rec = pool._do_get()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    fairy = _ConnectionRecord.checkout(pool)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    return _ConnectionFairy._checkout(self)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return fn()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return self._wrap_pool_connect(self.pool.connect, _connection)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    else engine.raw_connection()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    return self._connection_cls(self, close_with_result=close_with_result)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    engine.connect().close()
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    init(self, bind)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    return Inspector._construct(Inspector._init_engine, bind)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    ret = reg(subject)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    insp = inspection.inspect(autoload_with)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 710, in _autoload
    self._autoload(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 677, in _init
    table._init(name, metadata, *args, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 602, in __new__
    raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    compat.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    metadata._remove_table(name, schema)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 607, in __new__
    return fn(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
File "<string>", line 2, in __new__
    self.table = Table(table_name, metadata, autoload=True, autoload_with=engine)
File "/app/managers/ch_manager/ch_manager.py", line 287, in json_to_sql
    sql_query = ch_manager.get_instance().json_to_sql(global_filters, table_name, time_range)
File "/app/handler/segments/operations.py", line 113, in get_model_data
    data = get_model_data(global_filters, model_id, time_range, user_id)
File "/app/handler/segments/service.py", line 67, in view_segments_api
    data = view_segments_api(
File "/app/handler/segments/router.py", line 141, in view_segments
    status, response_object = function(*args, **kwargs)
File "/app/common/decorators.py", line 47, in wrapped_function
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<URL>', port=8123): Max retries exceeded with url: /?query_id=33d82c7f-da51-4968-8a4c-7da7041b5eea&database=analyzedb&default_format=TabSeparatedWithNamesAndTypes 
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb86a2097f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
Traceback (most recent call last):
```

**To Reproduce**
I am not able to reproduce on -- I even try to make 2K parallel fetch with same configuration as mentioned below
* It is only happening in Server with below configuration on Python application
```

    def get_engine_and_metadata(self):
        engine = create_engine(
            self.url,
            echo_pool=True,
            pool_recycle=3600,
            pool_size=30,
            max_overflow=30,
            pool_timeout=1,
        )
        metadata = MetaData(bind=engine)
        print(" [INFO]  CREATING ENGINE")

        return engine, metadata

    def get_session(self, engine=None):
        if engine is None:
            engine = self.engine
            session_maker = self.session_maker
        else:
            session_maker = sessionmaker(bind=engine)
        session = scoped_session(session_maker)
        return session

    def create_client(self):
        logging.info("ClickhouseManager: Creating clickhouse client")
        client = Client(
            host=os.environ["CH_HOST"],
            user=os.environ["CH_USER"],
            password=os.environ["CH_PASSWORD"],
            database=os.environ["CH_DB"],
            settings={"use_numpy": False, "max_threads": 8},
        )
        return client
```

Common decorator for executing CH is using our custom  `with_session` decorator
```
def with_session(func):

    session = get_instance().get_session()

    @wraps(func)
    def session_func(*args, **kwargs):
        res = func(*args, **kwargs, session=session)
        session.commit()
        session.close()
        return res

    return session_func
```

**Expected behaviour**
* Consistent behaviour of SQL alchemy without timeouts

**Versions**

- Version of package with the problem.
- clickhouse-driver==0.2.4
- clickhouse_sqlalchemy==0.2.2
- Python version = python:3.8.5

Not sure, are we missing anything on pool configuration. Although we are specifically using `scoped_session` approach to avoid any commit conflicts for simultaneous threads.

Any help would be appreciated. Thanks

**Comment by gr8Adakron** [comment]
This got resolved, found another function where multiple `engine` creation call
