### ISSUE TITLE
Query execution raises exception when using raw connection

### ISSUE THREAD

**Issue by AchilleAsh** [xzkostyan/clickhouse-sqlalchemy#39]
Hi,

We're having some issues with the driver under a use case which is using a raw connection.
How to reproduce:

```python
from sqlalchemy import create_engine, Column, MetaData, literal
from datetime import date, timedelta
from clickhouse_sqlalchemy import make_session, get_declarative_base, types, engines
uri = 'clickhouse+native://default:xxx@localhost/test'
engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)
Base = get_declarative_base(metadata=metadata)

class Rate(Base):
    day = Column(types.Date, primary_key=True)
    value = Column(types.Int32)
    __table_args__ = (
        engines.Memory(),
    )
table = Rate.__table__
table.create()
today = date.today()
rates = [{'day': today - timedelta(i), 'value': 200 - i} for i in range(100)]

# Emits single INSERT statement.
session.execute(table.insert(), rates) # This is fine
session.execute("SELECT * FROM rate") # Still OK

# now using a raw connection
raw = engine.raw_connection()
cur = raw.cursor()

qs = cur.execute("SELECT * FROM rate") # Boum

Traceback (most recent call last):
  File "/home/achille/.virtualenvs/clickhouse/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-392e6e940555>", line 1, in <module>
    qs = cur.execute("SELECT * FROM rate")
  File "/home/achille/clickhouse-sqlalchemy/clickhouse_sqlalchemy/drivers/native/connector.py", line 142, in execute
    external_tables, execute, settings = self._prepare(context)
  File "/home/achille/clickhouse-sqlalchemy/clickhouse_sqlalchemy/drivers/native/connector.py", line 115, in _prepare
    execution_options = context.execution_options
AttributeError: 'NoneType' object has no attribute 'execution_options'
```

So the problem is in fact simple and related to the last update of drivers/native/connector.py:

the `execute` and `executemany` methods of `Cursor` can take `context=None` as argument but `_prepare` does not handle this case and the very first line of it raises the exception:

```python
    def _prepare(self, context):
        execution_options = context.execution_options  # Here

        external_tables = self.make_external_tables(
            context.dialect, execution_options
        )

        transport = self._connection.transport
        execute = transport.execute
        execute_iter = getattr(transport, 'execute_iter', None)

        self._stream_results = execution_options.get('stream_results', False)
        settings = execution_options.get('settings')

        if self._stream_results and execute_iter:
            execute = execute_iter
            settings = settings or {}
            settings['max_block_size'] = execution_options['max_row_buffer']

        return external_tables, execute, settings

    def execute(self, operation, parameters=None, context=None):
        self._reset_state()
        self._begin_query()

        try:
            external_tables, execute, settings = self._prepare(context)
```
I have a working patch for this (well it's just a check on `context` no big deal), but as I'm not using any external tables I cannot test their usage with a raw_connection. However I think this particular usage may be ignored, so I'll make a PR to fix this.

Thanks for you work

**Comment by xzkostyan** [comment]
PR was merged. Closing this issue.
