### ISSUE TITLE
get_schema_names() doesn't work

### ISSUE THREAD

**Issue by villebro** [xzkostyan/clickhouse-sqlalchemy#64]
Trying to inspect schema and table names from an engine fails as the column name seems to be missing from the `ResultProxy` instance. Accessing it via the integer position works, but it seems accessing via name doesn't work as described by the API: https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.ResultProxy 

Example code:

```python
from sqlalchemy import create_engine, inspect

uri = 'clickhouse://default:@localhost'
engine = create_engine(uri)

print('Running manually')
res = engine.execute('SHOW DATABASES')
for row in res:
    print(row[0])  # has to be referenced by integer position to work

print('\nRunning via inspector')
insp = inspect(engine)
insp.get_schema_names()
````

Result:
```
Running manually
test

Running via inspector
Traceback (most recent call last):
  File "click.py", line 16, in <module>
    insp.get_schema_names()
  File "/Users/ville/.local/share/virtualenvs/incubator-superset-Q6iPzijF/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 160, in get_schema_names
    self.bind, info_cache=self.info_cache
  File "<string>", line 2, in get_schema_names
  File "/Users/ville/.local/share/virtualenvs/incubator-superset-Q6iPzijF/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 56, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/ville/.local/share/virtualenvs/incubator-superset-Q6iPzijF/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 560, in get_schema_names
    return [row.name for row in connection.execute('SHOW DATABASES')]
  File "/Users/ville/.local/share/virtualenvs/incubator-superset-Q6iPzijF/lib/python3.7/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 560, in <listcomp>
    return [row.name for row in connection.execute('SHOW DATABASES')]
AttributeError: Could not locate column in row for column 'name'
```

**Comment by xzkostyan** [comment]
Hi.

Long story short. You have two options:
- correct schema to native `uri = 'clickhouse+native://default:@localhost'`;
- patch `get_schema_names` to use `.execute('SHOW DATABASES FORMAT TabSeparatedWithNamesAndTypes')` if you want to use http driver.

There are two drivers for ClickHouse dialect in this package: http and native. Unfortunately I don't have time and efforts to support both of them. Therefore I'm focusing on native driver support. So, recommended schema for DSN is `clickhouse+native://`. But PRs for http driver are appreciated. Yep, `clickhouse+native` driver is not default right now.

Back to your problem. If you are using http driver and raw `engine.execute` you should add `FORMAT TabSeparatedWithNamesAndTypes` to your query for determining columns with their names. It seems to be valid  bug right now for http driver.

**Comment by xzkostyan** [comment]
Version 0.1.2 contains fix of this bug.

**Comment by xzkostyan** [comment]
@villebro should we close this issue?
