### ISSUE TITLE
Conda package enum34 issue

### ISSUE THREAD

**Issue by kszucs** [xzkostyan/clickhouse-sqlalchemy#7]
Hey @xzkostyan !

It misses `enum34`, even in python3.6
AFAIK it should not accorund to driver's [setup.py](https://github.com/mymarilyn/clickhouse-driver/blob/master/setup.py#L15)

Ideas?

```py
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    entrypoint = u._get_entrypoint()
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 139, in _get_entrypoint
    cls = registry.load(name)
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 214, in load
    return impl.load()
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2315, in load
    self.require(*args, **kwargs)
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/krisz/.pyenv/versions/ml3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34' distribution was not found and is required by clickhouse-driver
```

**Comment by xzkostyan** [comment]
Hi!

Current available on PyPI clickhouse-driver (0.0.6) https://github.com/mymarilyn/clickhouse-driver/blob/0.0.6/setup.py has this problem. Right, as you noticed future version (0.0.7) will contain this fix and `enum34` will not install for python 3.4+.

I'm waiting for secure sockets support that have been recently implemented: https://github.com/yandex/ClickHouse/blob/master/dbms/src/Client/Connection.cpp#L57.

I hope `v1.1.54299-testing` branch of CH will be published soon to deb repo so I can test this support. Afterwards 0.0.7 will be released.

**Comment by kszucs** [comment]
@xzkostyan Thanks! Any ideas as a workaround?

**Comment by kszucs** [comment]
Thanks!

**Comment by xzkostyan** [comment]
Hi!

I've bumped version to 0.0.7. It has no SSL support, but includes many fixes and optimizations. `enum34` will not be installed on python 3.4+.

**Comment by xzkostyan** [comment]
Hi, @kszucs.

Should we close this issue?

**Comment by kszucs** [comment]
Yes, thank You!
